events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    client_max_body_size 50M;

    upstream api {
        server api:8080;
    }

    upstream frontend {
        server frontend:80;
    }

    upstream minio {
        server minio:9001;
    }

    upstream pgadmin{
        server pgadmin:80;
    }

    server {
        listen 80;
        server_name _;

        # Required to prevent Nginx from dropping port 4000 on absolute redirects
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Angular SPA
        location / {
            proxy_pass http://frontend;
        }

        # Spring Boot API
        location /api/ {
            proxy_pass http://api;
            proxy_read_timeout 120s;
            proxy_request_buffering off;
        }

        # Minio Console Redirect (No trailing slash)
        location = /minio {
            return 301 $scheme://$http_host/minio/;
        }

        # Minio Console
        location /minio/ {
            proxy_pass http://minio/;
            proxy_read_timeout 120s;
            proxy_request_buffering off;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # pgAdmin Redirect (No trailing slash)
        location = /pgadmin {
            return 301 $scheme://$http_host/pgadmin/;
        }

        # pgAdmin
        location /pgadmin/ {
            proxy_pass http://pgadmin/;
            proxy_read_timeout 120s;
            proxy_request_buffering off;

            proxy_redirect off;
            proxy_set_header X-Script-Name /pgadmin;
        }

        # Health check endpoint
        location /health {
            proxy_pass http://api/api/actuator/health;
        }
    }
}
